version: "3.8"
services:
  api:
    container_name: "restApi"
    build:
      context: .
      dockerfile: "Dockerfile"
    ports:
      - "3000:3000"
    depends_on:
      - "mongo"
    volumes:
      - ./logs:/var/www/logs
    networks:
      - "app-network"
    links:
      - "mongo"

  mongo:
    image: mongo:4.2
    ports:
      - "27017:27017"
    container_name: mongo
    networks:
      - "app-network"
    volumes:
      - /data/db
  proxy:
    image: nginx:1.17
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - "app-network"
    links:
      - "api"
networks:
  app-network:
    driver: bridge
