version: "3.8"
services:
  api:
    build:
      context: .
      dockerfile: "Dockerfile"
    ports:
      - "3000:3000"
    container_name: nodejs-api
    depends_on:
      - "mongo"
    volumes:
      - ./logs:/var/www/logs
    networks:
      - "app-network"
    links:
      - "mongo"

  mongo:
    image: mongo:4.2
    ports:
      - "27017:27017"
    container_name: mongo
    networks:
      - "app-network"
    volumes:
      - /data/db

networks:
  app-network:
    driver: bridge
